server:
  port: 8802

spring:
  application:
    name: first-service
  datasource:
    url: jdbc:postgresql://localhost:5432/guest
    username: postgres
    password: 1234
  flyway:
    schemas: public
    user: postgres
    password: 1234
    enabled: true
