server:
  port: 8801

spring:
  application:
    name: guest-service
  datasource:
    url: jdbc:postgresql://localhost:5432/guest
    username: postgres
    password: 1234
  flyway:
    schemas: public
    user: postgres
    password: 1234
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka